Exp_name: 'exp1_av'

Modality: 'audio_video'

Training:
    Batch_size: 20
    Max_epoch: 200
    learning_rate: 1e-4
    seed: 25
    classes_num: 4
    modality_drop: 0.5
    audio_drop: 0.5

Audio_features:
    sample_rate: 64000
    window_size: 2048
    hop_size: 1024
    mel_bins: 128
    fmin: 1
    fmax: 128000


Workspace: 'AV_KL_workspace'
